/* tslint:disable */
/* eslint-disable */
/**
 * Futr Enterprise API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteDocumentDto
 */
export interface DeleteDocumentDto {
    /**
     * Document ID to delete
     * @type {string}
     * @memberof DeleteDocumentDto
     */
    id: string;
    /**
     * What to delete:
     * - 'file' (default): delete only the stored file from disk
     * - 'metadata': delete only the metadata (OCR results, markdown chunks) without touching the file
     * - 'both': delete the file and all associated metadata
     * @type {DeleteDocumentDtoTargetEnum}
     * @memberof DeleteDocumentDto
     */
    target?: DeleteDocumentDtoTargetEnum;
}


/**
 * @export
 */
export const DeleteDocumentDtoTargetEnum = {
    File: 'file',
    Metadata: 'metadata',
    Both: 'both'
} as const;
export type DeleteDocumentDtoTargetEnum = typeof DeleteDocumentDtoTargetEnum[keyof typeof DeleteDocumentDtoTargetEnum];


/**
 * Check if a given object implements the DeleteDocumentDto interface.
 */
export function instanceOfDeleteDocumentDto(value: object): value is DeleteDocumentDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function DeleteDocumentDtoFromJSON(json: any): DeleteDocumentDto {
    return DeleteDocumentDtoFromJSONTyped(json, false);
}

export function DeleteDocumentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteDocumentDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'target': json['target'] == null ? undefined : json['target'],
    };
}

export function DeleteDocumentDtoToJSON(json: any): DeleteDocumentDto {
    return DeleteDocumentDtoToJSONTyped(json, false);
}

export function DeleteDocumentDtoToJSONTyped(value?: DeleteDocumentDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'target': value['target'],
    };
}

