/* tslint:disable */
/* eslint-disable */
/**
 * Futr Enterprise API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteDocumentDto
 */
export interface DeleteDocumentDto {
    /**
     * Document ID to delete
     * @type {string}
     * @memberof DeleteDocumentDto
     */
    id: string;
    /**
     * Whether to also delete metadata (true) or just soft-delete the file (false)
     * @type {boolean}
     * @memberof DeleteDocumentDto
     */
    deleteMetadata?: boolean;
}

/**
 * Check if a given object implements the DeleteDocumentDto interface.
 */
export function instanceOfDeleteDocumentDto(value: object): value is DeleteDocumentDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function DeleteDocumentDtoFromJSON(json: any): DeleteDocumentDto {
    return DeleteDocumentDtoFromJSONTyped(json, false);
}

export function DeleteDocumentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteDocumentDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'deleteMetadata': json['deleteMetadata'] == null ? undefined : json['deleteMetadata'],
    };
}

export function DeleteDocumentDtoToJSON(json: any): DeleteDocumentDto {
    return DeleteDocumentDtoToJSONTyped(json, false);
}

export function DeleteDocumentDtoToJSONTyped(value?: DeleteDocumentDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'deleteMetadata': value['deleteMetadata'],
    };
}

