/*
Futr Enterprise API Documentation

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeleteDocumentDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteDocumentDto{}

// DeleteDocumentDto struct for DeleteDocumentDto
type DeleteDocumentDto struct {
	// Document ID to delete
	Id string `json:"id"`
	// Whether to also delete metadata (true) or just soft-delete the file (false)
	DeleteMetadata *bool `json:"deleteMetadata,omitempty"`
}

type _DeleteDocumentDto DeleteDocumentDto

// NewDeleteDocumentDto instantiates a new DeleteDocumentDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteDocumentDto(id string) *DeleteDocumentDto {
	this := DeleteDocumentDto{}
	this.Id = id
	var deleteMetadata bool = false
	this.DeleteMetadata = &deleteMetadata
	return &this
}

// NewDeleteDocumentDtoWithDefaults instantiates a new DeleteDocumentDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteDocumentDtoWithDefaults() *DeleteDocumentDto {
	this := DeleteDocumentDto{}
	var deleteMetadata bool = false
	this.DeleteMetadata = &deleteMetadata
	return &this
}

// GetId returns the Id field value
func (o *DeleteDocumentDto) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DeleteDocumentDto) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DeleteDocumentDto) SetId(v string) {
	o.Id = v
}

// GetDeleteMetadata returns the DeleteMetadata field value if set, zero value otherwise.
func (o *DeleteDocumentDto) GetDeleteMetadata() bool {
	if o == nil || IsNil(o.DeleteMetadata) {
		var ret bool
		return ret
	}
	return *o.DeleteMetadata
}

// GetDeleteMetadataOk returns a tuple with the DeleteMetadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteDocumentDto) GetDeleteMetadataOk() (*bool, bool) {
	if o == nil || IsNil(o.DeleteMetadata) {
		return nil, false
	}
	return o.DeleteMetadata, true
}

// HasDeleteMetadata returns a boolean if a field has been set.
func (o *DeleteDocumentDto) HasDeleteMetadata() bool {
	if o != nil && !IsNil(o.DeleteMetadata) {
		return true
	}

	return false
}

// SetDeleteMetadata gets a reference to the given bool and assigns it to the DeleteMetadata field.
func (o *DeleteDocumentDto) SetDeleteMetadata(v bool) {
	o.DeleteMetadata = &v
}

func (o DeleteDocumentDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteDocumentDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.DeleteMetadata) {
		toSerialize["deleteMetadata"] = o.DeleteMetadata
	}
	return toSerialize, nil
}

func (o *DeleteDocumentDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteDocumentDto := _DeleteDocumentDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeleteDocumentDto)

	if err != nil {
		return err
	}

	*o = DeleteDocumentDto(varDeleteDocumentDto)

	return err
}

type NullableDeleteDocumentDto struct {
	value *DeleteDocumentDto
	isSet bool
}

func (v NullableDeleteDocumentDto) Get() *DeleteDocumentDto {
	return v.value
}

func (v *NullableDeleteDocumentDto) Set(val *DeleteDocumentDto) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteDocumentDto) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteDocumentDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteDocumentDto(val *DeleteDocumentDto) *NullableDeleteDocumentDto {
	return &NullableDeleteDocumentDto{value: val, isSet: true}
}

func (v NullableDeleteDocumentDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteDocumentDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


